# Generated by Django 4.0.1 on 2022-01-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Driveway', 'Driveway'), ('Lot', 'Lot'), ('Garage', 'Garage'), ('Street', 'Street'), ('Other', 'Other')], default='Street', max_length=15)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
