# Generated by Django 4.0.1 on 2022-01-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feature_spot_description_spot_user_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
