# Generated by Django 4.0.1 on 2022-01-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_spot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='user',
        ),
    ]
