# Generated by Django 4.0.1 on 2022-01-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_spot_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='Features',
            new_name='features',
        ),
    ]
