# Generated by Django 4.0.1 on 2022-01-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_spot_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='location',
            new_name='address',
        ),
    ]
