# Generated by Django 4.0.1 on 2022-01-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_location_spot_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
